### ISSUE TITLE
AttributeError: module 'torchac.torchac' has no attribute 'CUDA_SUPPORTED'

### ISSUE THREAD

**Issue by rpitonak** [fab-jul/L3C-PyTorch#28]
Hello,

I have been trying to compress the image using this command:

```
python3 l3c.py --device cpu log_dir 0306_0001 enc ../../sample_data/img.png out.l3c
```

Output:

```
*** AC_NEEDS_CROP_DIM = 3000000
Using /root/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /root/.cache/torch_extensions/torchac_backend/build.ninja...
Building extension module torchac_backend...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module torchac_backend...
Traceback (most recent call last):
  File "l3c.py", line 129, in <module>
    main()
  File "l3c.py", line 111, in main
    parse_device_flag(flags.device)
  File "l3c.py", line 46, in parse_device_flag
    print(f'Status: '
AttributeError: module 'torchac.torchac' has no attribute 'CUDA_SUPPORTED'
```

I have installed `torchac` using pip from https://github.com/fab-jul/torchac

```
Requirement already satisfied: torchac in /usr/local/lib/python3.7/dist-packages (0.9.3)
```

Thank you for your help in advance.

**Comment by fab-jul** [comment]
Hi unfortunately `pip install torchac` is not the same as the torchac needed for L3C :)
Sorry for this confusion.
To run L3C, follow the installation instructions here: https://github.com/fab-jul/L3C-PyTorch#the-torchac-module-fast-entropy-coding-in-pytorch

**Comment by rpitonak** [comment]
Thank you, after installing from src/torchac it worked like a charm :) Closing the issue...
